
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dlh_demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dlh_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Schema configuration aligns with data warehouse layers:
# All schemas created in nessie catalog
# - raw: Source data
# - normalized: Cleaned and joined data  
# - presentation: Business-ready models
models:
  dlh_demo:
    
    # Normalized layer - cleaned and joined source data
    normalized:
      +materialized: table
      +database: nessie
      +schema: dlh_demo_normalized
    
    # Presentation layer - business-ready models
    presentation:
      +materialized: table
      +database: nessie
      +schema: dlh_demo_presentation

# Snapshot configuration - no schema prefix
snapshots:
  dlh_demo:

# Variables - default values
vars:
  snapshot_lookback_days: 30  # Default to checking last 30 days for snapshot changes

# Test configuration - set default severity levels
tests:
  dlh_demo:
    # By default, make all tests warnings (can override in individual tests)
    # +severity: warn
